### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ocp-index'

### ISSUE THREAD

**Issue by mationai** [whitequark/sublime-ocp-index#11]
I have ocp-index installed, running it in command line works.  But sublimetext console keeps saying:

File "/Users/john/Library/Application Support/Sublime Text 3/Packages/sublime-ocp-index/sublime_ocp_index.py", line 51, in run_ocp
    stderr=subprocess.PIPE)
  File "X/subprocess.py", line 818, in **init**
  File "X/subprocess.py", line 1416, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'ocp-index'

I tried everything, reinstall pkg, restart sublimetext, reboot OS, still error.

Running OSX Mavericks.

**Comment by whitequark** [comment]
If you use opam, you need to import the result of `opam config env` into environment before running Sublime Text.  Try invoking it from a shell, it should work.

**Comment by mationai** [comment]
Thanks for the fast reply. I added the path to os.environ in sublime_ocp_index.py and no more error.  There's other issue when using query_completions, but I'll ask that in a new issue.

Do you know if I can add path in my user sublime-settings instead?

**Comment by whitequark** [comment]
I think you should set it up in your OS somehow. Sublime is not the right tool to handle this.

**Comment by mationai** [comment]
You're right, thanks.

Thanks again for the quick help!

**Comment by TheSpyder** [comment]
The SublimeFixMacPath plugin will fix that for you :)
