### ISSUE TITLE
ocp-index: Unknown option '--format'

### ISSUE THREAD

**Issue by mationai** [whitequark/sublime-ocp-index#12]
When auto completing, a small dialog pops up saying:

ocp-index: Unknown option '--format' ...

Running ocp-index command, I do not see options for --format, --show, nor --hide, but I see them in the python code:

['--format', '%q %p %k %t', '--show', show, '--hide', hide],

**Comment by whitequark** [comment]
Your ocp-index is too old. You need to use the trunk version (or an earlier revision of sublime-ocp-index).

**Comment by mationai** [comment]
The latest seems to be 1.0.2 and I have that.  How do I tell opam to install/upgrade to trunk?  (Sorry to ask that here, can't find in http://opam.ocaml.org/doc/Advanced_Usage.html & can't google it).

**Comment by whitequark** [comment]
`opam pin ocp-index git://github.com/OCamlPro/ocp-index`
