### ISSUE TITLE
Completing variables with 2 or more underscores inserts whole variable

### ISSUE THREAD

**Issue by TheSpyder** [whitequark/sublime-ocp-index#7]
Start with something simple:

```
let big_variable_name = "big"

big_var<complete here>
```

ocp-index will offer "big_variable_name" as a completion, but notice that only the "var" is bold. If you accept this completion you will get `big_big_variable_name`.

This doesn't happen when there is only one underscore. I think it has to do with underscores being word separators in normal sublime logic.

**Comment by whitequark** [comment]
Yup. I have noticed this, but never got around to figuring out why sublime's autocomplete is broken here.

**Comment by TheSpyder** [comment]
It looks like you had figured this out - the first string in the tuple is what should be displayed to the user, the second is what should be inserted when the completion is selected.

But then you hard coded the length to zero. I'm now glad I kept that commented out code :)

**Comment by TheSpyder** [comment]
Looks like it isn't that simple after all. After my change, when no underscores are involved sublime's completion deletes the module name.

`Pervasives.inv<tab>` works (`Pervasives.invalid_arg`)
`Pervasives.re<tab>` fails (`ref`)

I wonder if that's a bug in sublime 3.

**Comment by TheSpyder** [comment]
I confirmed the behaviour in sublime 2, so I just put in a workaround for now. We might need to investigate further and/or log a bug with sublime at some point.

**Comment by whitequark** [comment]
I've been using sublime-ocp-index trunk for a while and never noticed this. So, closing. Feel free to reopen!
