### ISSUE TITLE
blocks communicating with the child process

### ISSUE THREAD

**Issue by ancillaryCode** [whitequark/sublime-ocp-index#9]
The reads from sdtin and stderr of child sequentially. The problem is this can block if the child is writing to the other fd. As far as I can tell, the correct solution is to use the "communicate" method off the proc object. I'd submit a patch but my employer has wrapped a bunch of bureaucracy around open source contributions.

**Comment by whitequark** [comment]
Thanks, I'll take a look. If attribution is a problem for you, you can mail a patch to whitequark@whitequark.org and I'll commit it under my name.

**Comment by TheSpyder** [comment]
Took a look at the python docs, and it seems easy enough. I ran a few tests and it still works, so...
